<?php
$h = $this->getHelper();
$baseUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);
?>

<?php if ($h->includeJquery()){ ?>
  <script type="text/javascript" src="<?php echo $baseUrl; ?>/frontend/base/default/js/jquery-3.4.1.min.js"></script>
<?php } ?>

<script type="text/javascript" src="<?php echo $baseUrl; ?>/frontend/base/default/js/handlebars.min.js"></script>
<script type="text/javascript" src="<?php echo $baseUrl; ?>/frontend/base/default/js/typeahead.jquery.min.js"></script>
<script type="text/javascript" src="<?php echo $baseUrl; ?>/frontend/base/default/js/logshub.js"></script>
<link rel="stylesheet" type="text/css" href="<?php echo $baseUrl; ?>/frontend/base/default/css/logshub.min.css" media="all" />
<script type="text/javascript">
var LhDefault = {
    'domain': '<?php echo $h->getApiDomain(); ?>',
    'pubKey': '<?php echo $h->getApiPublicKey(); ?>',
    'container': '<?php echo $h->getHtmlContainerSelector(); ?>',
    'fullscreen': <?php echo $h->getFullscreen(); ?>,
    'limit': <?php echo $h->getApiProductsLimit(); ?>,
    'categoryLimit': <?php echo $h->getApiCategoriesLimit(); ?>,
    'features': '<?php echo $h->getApiFeatures(); ?>',
    'startupQuery': '<?php echo $h->getStartupQuery(); ?>',
    'currency': '<?php echo $h->getDefaultCurrency(); ?>'
};

window.addEventListener('load', function () {
    const demo6 = new LogsHubAutoComplete({
      domain: LhDefault.domain,
      pubKey: LhDefault.pubKey,
      container: LhDefault.container,
      classNames: {
        dataset: 'tt-dataset tt-dataset--aside',
        menu: 'tt-menu tt-menu--aside',
        suggestion: 'tt-suggestion--aside'
      },
      fullscreen: LhDefault.fullscreen,
      limit: LhDefault.limit,
      categoryLimit: LhDefault.categoryLimit,
      defaultCurrency: LhDefault.currency,
      features: LhDefault.features,
      startupQuery: LhDefault.startupQuery,
      onSubmit: function(event){
        var query = (event.currentTarget.getElementsByClassName('tt-input')[0] || {}).value;
        window.location.href = '/search?controller=search&s=' + query;
      },
      onSelect: function(event, suggestion, dataset){
        if (suggestion.url){
          window.location.href = suggestion.url;
        }
      },
      datasets: [{
        features: 'categories',
        templates: {
          suggestion: Handlebars.compile(jQuery('#template-categories-demo-6').html()),
          notFound: ''
        }
      }, {
        features: 'products',
        templates: {
          suggestion: Handlebars.compile(jQuery('#template-products-demo-6').html()),
          notFound: ''
        }
      }]
    });
    demo6.init();
}, false);
</script>

<script id="template-categories-demo-6" type="text/x-handlebars-template">
    <div class="lh-result-row">
        {{name}}
    </div>
</script>
<script id="template-products-demo-6" type="text/x-handlebars-template">
    <div class="lh-result-row">
        {{#if url_image}}
            <div class="image-container"><img class="image image--big" src="{{url_image}}" alt=""/></div>
        {{/if}}

        <div class="details details--big">
        <span class="name">{{name}}</span>

        {{#if price}}
            <span class="price">{{price}} {{currency}}</span>
        {{/if}}

        {{#each categories}}
            <span class="category">{{this}}</span>
        {{/each}}
        </div>
    </div>
</script>

<style type="text/css">
<?php echo $this->getDefaultThemeStyles(); ?>
</style>